spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/cinema-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
    username: ${EMAIL}
    password: ${PASSWORD}
    smtp:
      start-tls-enable: true
      auth: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret-key: ${SECRET-KEY}
